# # Use uma imagem base oficial do Python
# FROM python:3.11.9-slim

# # Defina o diretório de trabalho
# WORKDIR /app

# # Copie o arquivo de requisitos para o contêiner
# COPY ./app/requirements.txt /app/requirements.txt

# # Instale as dependências necessárias
# RUN pip install --no-cache-dir -r /app/requirements.txt

# # Copie o conteúdo da aplicação para o contêiner
# COPY ./app /app

# # Comando para iniciar o servidor uvicorn
# CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
