# Define a imagem base
FROM python:3.9-slim-buster

# Define o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copia os arquivos do projeto para o contêiner
COPY . /app

# Instala as dependências do projeto
RUN apt-get update && \
    apt-get install -y postgresql-client && \
    apt-get install -y postgis && \
    pip install -r requirements.txt

# Define as variáveis de ambiente necessárias
ENV POSTGRES_HOST=<host_do_postgres>
ENV POSTGRES_PORT=<porta_do_postgres>
ENV POSTGRES_USER=<usuário_do_postgres>
ENV POSTGRES_PASSWORD=<senha_do_postgres>
ENV POSTGRES_DB=<nome_do_banco_de_dados>

# Expõe a porta necessária para o projeto
EXPOSE 8000

# Define o comando de inicialização do projeto
CMD <comando_de_inicialização_do_projeto>