# version: '3.8'
# services:
#   app:
#     image: python:3.11.9-slim
#     ports:
#       - 80:80
#     environment:
#       - NODE_ENV=production
#     volumes:
#       - ./app:/app
#     restart: always
#     depends_on:
#       - db

#   db:
#     image: postgis/postgis:15-3.3
#     environment:
#       POSTGRES_DB: ${POSTGRES_DB}
#       POSTGRES_USER: ${POSTGRES_USER}
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#     volumes:
#       - ./db:/var/lib/postgresql/data
#       - ./db/init-postgis.sh:/docker-entrypoint-initdb.d/init-postgis.sh
#     restart: always

# # Opcional: especifica o arquivo de ambiente a ser usado
# env_file:
#   - .env
