name: Spotsat Challenge Workflow - Continuous Integration

on:
  push:
    branches: ["challenge"]
  pull_request:
    branches: ["challenge"]

permissions:
  contents: read

jobs:
  run-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgis/postgis:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: geodb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          cd app
          pip install -r requirements.txt

      - name: Set environment variables
        run: |
          echo "USER=postgres" >> $GITHUB_ENV
          echo "PASSWORD=postgres" >> $GITHUB_ENV
          echo "HOST=localhost" >> $GITHUB_ENV
          echo "PORT=5432" >> $GITHUB_ENV

      - name: Wait for Postgres to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            sleep 1
          done

      - name: Create PostGIS extension
        env:
          PGPASSWORD: postgres
        run: |
          psql -h localhost -U postgres -d geodb -c "CREATE EXTENSION postgis;"

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        run: pytest
